name: syncup_music_app
description: "Plataforma de streaming y descubrimiento social de música."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  permission_handler: ^11.3.0 
  http: ^0.13.6
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
